import { Plus_Jakarta_Sans } from 'next/font/google'

const jakarta = Plus_Jakarta_Sans({
  weight: ['400', '500', '600', '700'],
  style: ['normal', 'italic'],
  subsets: ['latin-ext'],
})

export const metadata = {
  title: 'Leadster Test Igor',
  description: 'Generated by create next app',
}

export default function RootLayout({children}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br">
      <body className={jakarta.className}>{children}</body>
    </html>
  );
}
